### PR TITLE
Fix broken image.

### PR DESCRIPTION
**Pull request by NPDebs**
Signed-off-by: Deborah Udoh <deborahudoh02@gmail.com>

**Description**
This PR fixes issue #371 

readme-img

**Notes for Reviewers**
The broken image was fixed by editing line 34, to change the file format (from SVG to PNG).  Thank you.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Looking good, @NPDebs

**Comment by leecalcote** [comment]
@NPDebs, oh, I just noticed that there are two sets of the community images. Will you take a look at the other repos’ readmes and make this one similar?

**Comment by NPDebs** [comment]
Sure Mr @leecalcote . Right away. 🏃🏽‍♀️💨

**Comment by NPDebs** [comment]
Wow. I just noticed that only one image shows up in the other repos.

I've made the necessary changes on my fork. Shall I open a new PR?  || @leecalcote

**Pull request merged**
