### PR TITLE
Update approve-to-run-ci.yml

### LINKED ISSUE #474: CI: The build test is not working and it should be fixed.
#### Current Behavior

The current build checking step has a condition below
https://github.com/meshery/meshery-operator/blob/27cfe5f0a3df642b88681bbac252e98757885749/.github/workflows/approve-to-run-ci.yml#L53

However, even though the PR was approved or the comment includes an LGTM. The CI is still not being triggered. 

#### Expected Behavior

The CI can be triggered by LGTM/approved, or we can add requirements for it after `codecov` and `golangci-lint` were successful.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by duckling69**
**Description**

This PR fixes #474 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by leecalcote** [comment]
If we're going to move forward with commands like this, all repos should support this behavior universally and consistently.

Command should be prepended with `/` so as to avoid clashing with commonly used comments like the one that @Aisuko gave above.

Please raise this PR and this question in the discuss.layer5.io forum as a proposal for change across all repos.

**Comment by leecalcote** [comment]
Also, I generally agree with @Aisuko in terms of this PR: LGTM. Let's review as a broader proposal, though.

**Comment by Aisuko** [comment]
> If we're going to move forward with commands like this, all repos should support this behavior universally and consistently.
> 
> Command should be prepended with `/` so as to avoid clashing with commonly used comments like the one that @Aisuko gave above.
> 
> Please raise this PR and this question in the discuss.layer5.io forum as a proposal for change across all repos.

Will do.

**Comment by Aisuko** [comment]
Hi @duckling69 , May you help check the why the Build CI was not triggered? I believe it is not too much useful. And we can change to the simple one which is only adding `need` key word for the `Build` job.

**Comment by Aisuko** [comment]
> > Hi @duckling69 , May you help check the why the Build CI was not triggered? I believe it is not too much useful. And we can change to the simple one which is only adding `need` key word for the `Build` job.
> 
> Will have a look into it

Hi @duckling69 
If it is not working so well, let's add a `need: [job1, job2]` condition for the build job. And we can get a quick merge.

**Comment by duckling69** [comment]
> > > Hi @duckling69 , May you help check the why the Build CI was not triggered? I believe it is not too much useful. And we can change to the simple one which is only adding `need` key word for the `Build` job.
> > 
> > 
> > Will have a look into it
> 
> Hi @duckling69 If it is not working so well, let's add a `need: [job1, job2]` condition for the build job. And we can get a quick merge.

Sure done

**Pull request merged**
