### PR TITLE
Update README.md [[Docs] readme: support light and dark mode image versions of Meshery logo]

### LINKED ISSUE #511: [Docs] readme: support light and dark mode image versions of Meshery logo
#### Desired State

See the other repositories for an example. 

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

### PR DESCRIPTION
**Pull request by Rajdeep1311**
**Description**

This PR fixes #511 

**Notes for Reviewers**
Thanks, Please review my PR and suggest if any changes needed

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thanks. Changes needed:

1. don't reference your own repo
2. use the raw.githubusercontent.com references
3. use image references that are of this repo (images must be in this repo).

**Comment by Rajdeep1311** [comment]
> Thanks. Changes needed:
> 
> 1. don't reference your own repo
> 2. use the raw.githubusercontent.com references
> 3. use image references that are of this repo (images must be in this repo).

Okay sir... On it

**Comment by Rajdeep1311** [comment]
@leecalcote sir can you tell me how to use or learn more about raw.githubusercontent.com

**Comment by Ghat0tkach** [comment]
@Rajdeep1311 , this isnt a valid issue . You may close this PR

**Comment by Ghat0tkach** [comment]
closing this as it isnt a valid issue , Thanks for you contribution @Rajdeep1311 . There are plenty of other issues , you may contribute there as well🙌

**Comment by Rajdeep1311** [comment]
Sure

**Pull request closed without merging**
