### PR TITLE
Update README.md

### LINKED ISSUE #523: [README.md] bold styling not applied to text
#### Current State
Currently all points under section: "Join the Meshery community!" have the first word or two italicized and bold styling added. However the third point "_Fill-in_ a [community member form](https://layer5.io/newcomers) to gain access to community resources.", has its first word "Fill-in" italicized, but does not have the bold styling applied. 

### Screenshots
imageedit_3_9131638095

#### Desired State
To maintain consistency, add bold styling to the text "Fill-in"

i.e "_**Fill-in**_  a [community member form](https://layer5.io/newcomers) to gain access to community resources."

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.meshery.io)

### PR DESCRIPTION
**Pull request by rohan472000**
**Description**

Made `Fill-in` bolder in readme of this repo.

This PR fixes #523 

Signed-off :    Rohan Anand anand00rohan@gmail.com

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by rohan472000** [comment]
@sandramsc review it.

**Comment by sandramsc** [comment]
> @sandramsc review it.
CC: @Mohith234 @Chadha93 @Modern-artist 
Hi, maintainers are the ones who generally review, merge PR's here, not necessarily the person who creates the issue.

**Comment by rohan472000** [comment]
Thanks for the clarification.

As this issue was really minute, had nothing to discuss over it much, so I raised the PR. Now I've seen the guidelines thoruoghly of this repo, so next time I'll get issue assigned first then PR.

**Review by Mohith234 — APPROVED** [review]
Appreciate your enthusiasm @rohan472000 , Please do not create any PRs unless the issue is assigned to you. Read the contributing guidelines beforehand.

**Review by leecalcote — APPROVED** [review]
Looks great. Thank you, @rohan472000 👍

**Comment by leecalcote** [comment]
Ready for your next issue, @rohan472000?

**Comment by rohan472000** [comment]
> Ready for your next issue, @rohan472000?

Yeah sure :)

**Pull request merged**
