### PR TITLE
Upgrade/1.19

### PR DESCRIPTION
**Pull request by acald-creator**
**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by acald-creator** [comment]
Whatever is available for the workflows will pass, however I have not tested for the release workflow.

**Comment by leecalcote** [comment]
I can help test. Before I do, have you already run this version of the Operator in a Kubernetes environment?

**Comment by acald-creator** [comment]
I did, but I will test again either way.

**Review by leecalcote — APPROVED** [review]
Looking real good. 👍

**Pull request merged**
