### PR TITLE
[Docs]Support light vs dark mode display of Meshery logo in README

### LINKED ISSUE #314: [Docs]Support light vs dark mode display of Meshery logo in README
#### Current State
There are some logos in README.md that have very low contrast in either light/dark mode 

#### Desired State
Change the docs such that there is a separate logo for dark/light mode with high contrast

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by K0more**
**Description**

This PR fixes #314 

**Notes for Reviewers**
Fixed the typo in logo img source code.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
signed-off-by: k0more <arch.phenon@gmail.com>

### CODE REVIEW

**Comment by K0more** [comment]
@leecalcote I have made the changes, could you review it for any suggestions.

**Comment by leecalcote** [comment]
Thanks, @K0more. There's a merge conflict to address.

**Comment by K0more** [comment]
@leecalcote fixed it, lmk if there are any suggestions.

**Comment by Nikhil-Ladha** [comment]
@leecalcote do we intend to use the gray version of the operator logo here?
As per the brand guide: https://layer5.io/company/brand

**Review by alphaX86 — COMMENTED** [review]
I'm seeing 2 logs 👀 is this intended @K0more ?

image

**Comment by K0more** [comment]
@alphaX86 woops, I didn't see that there were two communities anchors, ima fix this.

**Comment by leecalcote** [comment]
Thanks, @K0more !

**Comment by leecalcote** [comment]
I still see two of the community icon
Screen Shot 2022-10-07 at 4 45 10 PM
s, too.

**Comment by K0more** [comment]
@leecalcote yea there was some issue with my clone, I am tryna fix it rn. I'll update it by today (tomorrow for you).

**Pull request merged**
