### PR TITLE
the icons / logo's in README.md change accordingly to dark mode and light mode

### LINKED ISSUE #314: [Docs]Support light vs dark mode display of Meshery logo in README
#### Current State
There are some logos in README.md that have very low contrast in either light/dark mode 

#### Desired State
Change the docs such that there is a separate logo for dark/light mode with high contrast

---

#### [Contributor Guides](https://docs.meshery.io/project/contributing) and Resources
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

### PR DESCRIPTION
**Pull request by exitflynn**
**Description**

This PR fixes #314 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [✅] Yes, I signed my commits.

### CODE REVIEW

**Comment by exitflynn** [comment]
Previously: 
dark-mode:
image
light-mode:
image

Now:
dark-mode:
image
light-mode:
image

**Comment by leecalcote** [comment]
@bhavyastar, would you like to review this?

**Review by cpepper96 — APPROVED** [review]
LGTM

**Comment by chetak123** [comment]
Hey @exitflynn can you please squash the commits into a single commit.

**Comment by leecalcote** [comment]
@chetak123 its not a bad ask, however, commit squashing isn’t something practiced in this project.

**Review by bhavyastar — COMMENTED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by leecalcote — APPROVED** [review]
Thanks, all. 👍

**Pull request merged**
