### PR TITLE
Use DeepCopy instead of passing by reference

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #
Recently we were facing panic on operator due the fact that it tried to assert an array's index from a struct which was being manipulated because of being passed around by reference. This PR adds a DeepCopy  method to copy the original struct without changing it to avoid panic in future. 
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @Revolyssup. Do you recall under what circumstances we ran into this issue?

**Review by leecalcote — APPROVED** [review]
LGTM

**Review by MUzairS15 — APPROVED** [review]
LGTM

**Review by CyrineG — APPROVED** [review]

**Comment by Revolyssup** [comment]
> Thank you, @Revolyssup. Do you recall under what circumstances we ran into this issue?

Yes I have a hunch of what would have happened.

**Comment by leecalcote** [comment]
Ok, I'm curious to know the outcome.

**Pull request merged**
