### PR TITLE
Upgrade containerd version in order to fix security issue

### PR DESCRIPTION
**Pull request by Aisuko**
Signed-off-by: Aisuko <urakiny@gmail.com>

**Description**

https://github.com/meshery/meshery-operator/security/dependabot/17

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Aisuko** [comment]
I have been tested under the local environment

**Comment by leecalcote** [comment]
Thank you! I’m curious - are indirect dependencies overwritten when `go mod tidy` is run?

**Comment by Aisuko** [comment]
> Thank you! I’m curious - are indirect dependencies overwritten when `go mod tidy` is run?

Yes, `it adds missing module requirements necessary ... and it removes requirements on modules that do not provide any relevant packages. And it also adds any missing entries to go.sum and removes unnecessary entries. `  

https://go.dev/ref/mod#go-mod-tidy

**Comment by leecalcote** [comment]
@Aisuko ok, gotcha. This security patch will be temporary, then.

**Comment by Aisuko** [comment]
No problem, we need further to test it.

**Comment by leecalcote** [comment]
@Revolyssup where does our containerd dependency come from, do you know?

**Comment by Revolyssup** [comment]
> @Revolyssup where does our containerd dependency come from, do you know?

Meshkit

**Comment by leecalcote** [comment]
@Revolyssup even MeshKit's use is transitive - https://github.com/meshery/meshkit/blob/de874a5621cdede56970d5046856741e11e1cecb/go.mod#L60. Where are we in direct control of this dependency or aren't we?

**Comment by acald-creator** [comment]
This PR can be closed since we've already upgraded this project to Go 1.19 and most of the packages were upgrade appropriately.

**Pull request closed without merging**
