### PR TITLE
[chore] Bump NATS version

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — CHANGES_REQUESTED** [review]
Thanks for your contribution. Please give us a detail on this. Why we need bump the version to the latest?

**Comment by Aisuko** [comment]
Please help us investigate the error of the CI checking process.

**Comment by leecalcote** [comment]
Updating with master

**Comment by theBeginner86** [comment]
> Thanks for your contribution. Please give us a detail on this. Why we need bump the version to the latest?

I and Lee were discussing the need for upgrading the NATS version for **potentially reducing the security vulnerabilities we have on meshery repo**

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
