### PR TITLE
bump version from 3-alpha to 3

### PR DESCRIPTION
**Pull request by iamsdas**
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>

**Description**

Version 3-alpha is deprecated
This PR is related to issue #220

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — COMMENTED** [review]
I believe that we updated to the v3 is compatilty back forward for 3-alpha right?

**Comment by iamsdas** [comment]
The 3-alpha version is not supported by operator-sdk v1.5+ and gives `deprecation errors` when trying to make the bundle. There shouldn't be any compatibility issues if that's your question.

**Review by Aisuko — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
> The 3-alpha version is not supported by operator-sdk v1.5+ and gives `deprecation errors` when trying to make the bundle. There shouldn't be any compatibility issues if that's your question.

Thanks, the version related to `operator-sdk` rather than the resources deployment manifest.

**Pull request merged**
